events {}

http {
    upstream backend {
        server api:5000;
        # dynamically add GCP VM later
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}